### ISSUE TITLE
if using default /home/domoticz config page does not work

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon#9]
The config pages do load but they are not able to talk the serial port. 

I try on shell: 
./sendcmd.sh "0;1;2;0;26;1"
Sending: '0;1;2;0;26;1'
Got response: '0;1;1;0;26;0.0.022,0.0.013'
and seems fine, however it does not work on the IP/config page

The URL that loads the config file is: http://IP/?f=internal

@mattlogic @jjgarciajz

**Comment by jjgarciajz** [comment]
Can you confirm you have installed everything inside the /opt folder, following the Installation guide?

The Machinon installation instructions specify that Domoticz **must** be installed in /opt/domoticz

This has been made to keep everything out of the default 'pi' user and, also, because is (/opt) where the non repository applications should go in any linux machine.

**Comment by EdddieN** [comment]
No it is the default /home/pi one. It was there before installing the files and I cannot move it. Any other option?

**Comment by mattlogic** [comment]
If you installed the config forms and Nginx as per the Machinon install guide, then also make sure that the nginx `www-data` user has access rights for the tty/serial ports:
`sudo usermod -a -G dialout www-data`
This might need a restart of nginx to take effect.

Also check that the config php pages are using the correct serial port `/dev/ttySC1`, defined in `...config/includes/machinonSerial.php`. It should be OK in all of the current repo scripts and config forms.

**Comment by jjgarciajz** [comment]
Follow Matt's answer, I just checked installing domoticz on the default path won't affect the usage of the rest of services. So, it may be indeed some permissions issue.

**Comment by EdddieN** [comment]
This
sudo usermod -a -G dialout www-data
plus this
sudo service nginx restart
fixed it

**Comment by EdddieN** [comment]
Something again broken
![Screenshot 2019-04-03 at 18 52 21](https://user-images.githubusercontent.com/39434245/55501177-c3d6ad80-5641-11e9-9a63-c74605062b7a.png)

**Comment by EdddieN** [comment]
and now it works... it seems there's something with redirect / caching chrome, etc.?

**Comment by mattlogic** [comment]
The landing page with buttons for Domoticz and Config is now at the root `http://<IP>/` URL (which actually serves you `<IP>/index.php?f=main`). The earlier `<IP>/config` URL is not used any more, so the error 404 is OK. We could add another redirect so the config forms can be accessed via `<IP>/config`.

It looks like the Domoticz session cookie does not get deleted at logout if you access via the Machinon nginx proxy, so Domoticz either shows as "offline" or keeps showing the login page. If you access Domoticz directly at `<IP>:8080/` then the cookie is deleted (to force a new login/session at next access).

I suspect this is something to do with the cookie domain, or Domoticz not using the same domain for setting and deleting the cookie. Nginx should not be doing any caching, just passing the requests though.
